#!/usr/bin/env python3
"""The privacy policy, served by the MCP worker at /privacy, generated from the ONE
source the app renders (app/legal/privacy.tsx), so the two can never disagree."""
import re, json, html, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
src = (root / 'app/legal/privacy.tsx').read_text()
updated = re.search(r"styles\.updated}>([^<]+)<", src).group(1).strip()
intro = re.search(r"styles\.intro}>([^<]+)<", src).group(1).strip()
sections = []
for m in re.finditer(r'<Section title="([^"]+)">\s*(.*?)\s*</Section>', src, re.S):
    body = m.group(2).strip()
    if body.startswith("{'") and body.endswith("'}"):
        body = body[2:-2].replace("\\'", "'")
    sections.append((m.group(1), re.sub(r'\s+', ' ', body)))
assert len(sections) >= 12, len(sections)
parts = ''.join(f'<h2>{html.escape(t)}</h2><p>{html.escape(b)}</p>' for t, b in sections)
page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy Policy, The Living Bread</title><link rel="canonical" href="https://living-bread.org/legal/privacy">
<meta name="description" content="How The Living Bread collects, uses, shares, keeps and deletes personal data, including through AI assistants.">
<style>body{{margin:0;background:#F8F5EE;color:#1d2a33;font:16px/1.65 Georgia,serif}}main{{max-width:720px;margin:0 auto;padding:40px 20px 80px}}
h1{{font-size:32px;margin:0 0 6px}}.u{{font:600 12px/1 Helvetica,Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#6b7680}}
.i{{font-style:italic;color:#3c4a54}}h2{{font-size:21px;margin:30px 0 8px}}p{{margin:0}}a{{color:#8a6a1f}}</style></head>
<body><main><h1>Privacy Policy</h1><div class="u">{html.escape(updated)}</div><p class="i" style="margin-top:14px">{html.escape(intro)}</p>{parts}
<p style="margin-top:34px">Publisher: The Living Bread, 1414 12th Ave, Seattle, Washington, United States. Contact: <a href="mailto:support@living-bread.org">support@living-bread.org</a> · <a href="https://living-bread.org/support">living-bread.org/support</a></p></main></body></html>'''
(root / 'mcp/src/privacy.generated.ts').write_text('// generated by mcp/scripts/build-privacy.py from app/legal/privacy.tsx; do not edit\nexport const PRIVACY_HTML = ' + json.dumps(page) + ';\n')
print('sections', len(sections), 'bytes', len(page))
