/* ============================================================
   THE LIVING BREAD MCP, verses for a need.

   src/data/needs.json is generated by scripts/build-data.py from the same
   tables the web builder uses (verses_data NEEDS, build-landing
   VERSE_TOPICS, topics_data TOPICS, verse_topic_enrich), so the references
   here are the references on living-bread.org. It holds references and our
   own one-line reflections; the Scripture itself is read from the stored
   KJV at call time.

   Matching is deliberately forgiving: a person says "I'm scared" or "my
   mother died", not "fear" or "grief". Pure, so it can be tested anywhere.
   ============================================================ */
import NEEDS from './data/needs.json';

export interface NeedRef {
  ref: string;
  /** In our words, not His: a line on why this verse speaks here. */
  why?: string;
}

export interface Need {
  slug: string;
  label: string;
  lead: string;
  page: string;
  refs: NeedRef[];
}

const TABLE = NEEDS as Record<string, Omit<Need, 'slug'>>;

export function allNeeds(): Need[] {
  return Object.entries(TABLE).map(([slug, n]) => ({ slug, ...n }));
}

export function needBySlug(slug: string): Need | null {
  const n = TABLE[slug];
  return n ? { slug, ...n } : null;
}

/* What people actually say, mapped to the need slugs that exist. Order
   matters inside each list: the first slug that exists wins. */
const SYNONYMS: Record<string, string[]> = {
  scared: ['fear'], afraid: ['fear'], terrified: ['fear'], frightened: ['fear'], panic: ['fear', 'anxiety'],
  worried: ['anxiety', 'worry'], worry: ['worry', 'anxiety'], worrying: ['worry', 'anxiety'], anxious: ['anxiety'],
  stress: ['anxiety', 'peace'], stressed: ['anxiety', 'peace'], overwhelmed: ['anxiety', 'rest', 'strength'],
  sad: ['depression', 'comfort'], sadness: ['depression', 'comfort'], depressed: ['depression'], hopeless: ['hope', 'depression'],
  despair: ['hope', 'depression'], empty: ['depression', 'purpose'], numb: ['depression', 'comfort'],
  lonely: ['loneliness'], alone: ['loneliness'], isolated: ['loneliness'], abandoned: ['loneliness', 'gods-love'],
  died: ['grief'], death: ['grief'], funeral: ['grief'], loss: ['grief'], lost: ['grief', 'guidance'], mourning: ['grief'], grieving: ['grief'],
  widow: ['grief', 'comfort'], miscarriage: ['grief', 'comfort'],
  tired: ['rest', 'strength'], exhausted: ['rest', 'strength'], weary: ['rest', 'strength'], burnout: ['rest', 'strength'], burned: ['rest'],
  angry: ['anger'], furious: ['anger'], rage: ['anger'], resentment: ['bitterness', 'forgiving-others', 'anger'], bitter: ['bitterness', 'forgiving-others'],
  guilty: ['forgiveness', 'repentance'], guilt: ['forgiveness', 'repentance'], shame: ['forgiveness', 'identity'], ashamed: ['forgiveness', 'identity'],
  forgive: ['forgiving-others', 'forgiveness'], forgiven: ['forgiveness'], sinned: ['repentance', 'forgiveness'], failed: ['forgiveness', 'grace'], failure: ['forgiveness', 'grace'],
  hurt: ['broken-heart', 'comfort', 'healing'], heartbroken: ['broken-heart'], breakup: ['broken-heart'], divorce: ['broken-heart', 'marriage'], betrayed: ['broken-heart', 'forgiving-others'],
  sick: ['healing'], illness: ['healing'], cancer: ['healing', 'suffering'], hospital: ['healing', 'comfort'], pain: ['suffering', 'healing', 'comfort'], surgery: ['healing', 'fear'],
  money: ['money', 'provision'], bills: ['provision', 'money'], debt: ['money', 'provision'], broke: ['provision', 'money'], job: ['work', 'provision'], unemployed: ['provision', 'trust'], work: ['work'],
  marriage: ['marriage'], husband: ['marriage'], wife: ['marriage'], spouse: ['marriage'], wedding: ['marriage', 'love'],
  kids: ['children', 'family'], children: ['children'], child: ['children'], parenting: ['children', 'family', 'patience'], family: ['family'], parents: ['family'],
  friend: ['friendship'], friends: ['friendship'], friendship: ['friendship'],
  tempted: ['temptation'], temptation: ['temptation'], addiction: ['addiction', 'temptation'], addicted: ['addiction'], porn: ['purity', 'temptation'], lust: ['purity', 'temptation'], drinking: ['addiction', 'self-control'],
  doubt: ['doubt', 'faith'], doubting: ['doubt', 'faith'], unsure: ['doubt', 'guidance'], confused: ['guidance', 'wisdom'], decision: ['guidance', 'wisdom'], direction: ['guidance', 'gods-plan'],
  purpose: ['purpose', 'calling'], meaning: ['purpose'], calling: ['calling', 'purpose'], future: ['gods-plan', 'trust', 'hope'],
  waiting: ['waiting-on-god', 'patience'], patience: ['patience'], impatient: ['patience'],
  weak: ['strength'], strength: ['strength'], brave: ['courage'], courage: ['courage'], bold: ['boldness'],
  peace: ['peace'], calm: ['peace', 'rest'], rest: ['rest'], sleep: ['rest', 'peace', 'anxiety'], insomnia: ['rest', 'peace'],
  thankful: ['gratitude'], grateful: ['gratitude'], gratitude: ['gratitude'], joy: ['joy'], happy: ['joy'],
  saved: ['salvation'], salvation: ['salvation'], heaven: ['heaven', 'eternal-life'], eternal: ['eternal-life'], hell: ['salvation'],
  loved: ['gods-love'], unloved: ['gods-love', 'identity'], worthless: ['identity', 'gods-love'], identity: ['identity'], 'self-worth': ['identity'],
  proud: ['pride', 'humility'], pride: ['pride'], humble: ['humility'], jealous: ['jealousy', 'contentment'], envy: ['jealousy', 'contentment'], comparison: ['comparison', 'contentment'],
  enemy: ['enemies', 'forgiving-others'], enemies: ['enemies'], bullied: ['enemies', 'protection'], persecuted: ['enemies', 'suffering'],
  safe: ['protection'], safety: ['protection'], danger: ['protection', 'fear'], protection: ['protection'],
  old: ['aging'], aging: ['aging'], retirement: ['aging', 'purpose'],
  pray: ['prayer'], prayer: ['prayer'], praying: ['prayer'], worship: ['worship'], serve: ['serving'], serving: ['serving'],
  trust: ['trust'], faith: ['faith'], grace: ['grace'], mercy: ['mercy'], hope: ['hope'], love: ['love'], wisdom: ['wisdom'], truth: ['truth'],
  comfort: ['comfort'], encourage: ['encouragement'], encouragement: ['encouragement'], discouraged: ['encouragement', 'hope'],
  suffering: ['suffering', 'trials'], trial: ['trials'], trials: ['trials'], hard: ['trials', 'perseverance'], persevere: ['perseverance'],
  spirit: ['the-holy-spirit'], cross: ['the-cross'], tongue: ['the-tongue'], gossip: ['the-tongue'], words: ['the-tongue'], tithe: ['tithing', 'generosity'], giving: ['generosity'], generous: ['generosity'],
  honest: ['honesty'], lying: ['honesty', 'truth'], justice: ['justice'], unfair: ['justice', 'trust'], kind: ['kindness'], kindness: ['kindness'],
  obey: ['obedience'], obedience: ['obedience'], discipline: ['discipline', 'self-control'], holy: ['holiness'], pure: ['purity'], purity: ['purity'],
  warfare: ['spiritual-warfare'], attack: ['spiritual-warfare', 'protection'], devil: ['spiritual-warfare'], demons: ['spiritual-warfare'],
  bless: ['blessing'], blessing: ['blessing'], confidence: ['confidence'], content: ['contentment'], contentment: ['contentment'], relationship: ['relationships'], relationships: ['relationships'],
  evangelism: ['evangelism'], share: ['evangelism'], witness: ['evangelism'], 'end times': ['the-end-times'], apocalypse: ['the-end-times'], return: ['the-end-times'],
};

function words(s: string): string[] {
  return s.toLowerCase().replace(/[^a-z\s'-]/g, ' ').split(/\s+/).filter(Boolean);
}

export interface NeedMatch {
  need: Need;
  /** What in the question matched: a slug, a label, or a word people say. */
  matched: string;
}

/**
 * Find the need a person is naming. Exact slug or label first, then a
 * synonym of what they said, then a slug or label that appears inside the
 * sentence. Null when nothing fits, which the tool reports honestly.
 */
export function findNeed(query: string): NeedMatch | null {
  const q = (query || '').trim().toLowerCase();
  if (!q) return null;
  const slug = q.replace(/[\s_]+/g, '-').replace(/[^a-z-]/g, '');
  const direct = needBySlug(slug);
  if (direct) return { need: direct, matched: slug };
  for (const n of allNeeds()) {
    if (n.label.toLowerCase() === q) return { need: n, matched: n.label };
  }
  const ws = words(q);
  // multi word synonyms first ("end times")
  for (const [k, slugs] of Object.entries(SYNONYMS)) {
    if (k.includes(' ') && q.includes(k)) {
      for (const s of slugs) {
        const n = needBySlug(s);
        if (n) return { need: n, matched: k };
      }
    }
  }
  for (const w of ws) {
    const bare = w.replace(/'s$/, '');
    const n = needBySlug(bare);
    if (n) return { need: n, matched: bare };
    for (const s of SYNONYMS[bare] ?? []) {
      const hit = needBySlug(s);
      if (hit) return { need: hit, matched: bare };
    }
  }
  // a stemmed word: "grieving" -> "grief" is in SYNONYMS; "anxieties" -> anxiety
  for (const w of ws) {
    for (const n of allNeeds()) {
      const root = n.slug.replace(/-/g, ' ');
      if (w.length >= 5 && (root.startsWith(w.slice(0, 5)) || w.startsWith(root.slice(0, 5)))) {
        return { need: n, matched: w };
      }
    }
  }
  return null;
}
