/* ============================================================
   THE LIVING BREAD MCP, Scripture: references, never typed words.

   The rule of this house is that no verse is ever typed from memory. A tool
   holds a REFERENCE; the words come from the King James Version the app
   itself ships (assets/bible/books, read through the ASSETS binding) or from
   the World English Bible cache the repo already holds (src/data/web.json,
   generated by scripts/build-data.py). A reference that cannot be resolved
   returns null, which is honest, never a half remembered line.

   This file is pure: no bindings, no fetch, so it can be tested anywhere.
   ============================================================ */
import WEB from './data/web.json';
import { noteReading } from './evidence';

export interface BookMeta {
  id: string;
  name: string;
  chapters: number;
  aliases: string[];
}

/* The same 66 books, ids and names as components/bible/books.ts, plus the
   abbreviations people and assistants actually write. Aliases are matched
   with spaces and dots removed, lower case. */
export const BOOKS: BookMeta[] = [
  { id: 'genesis', name: 'Genesis', chapters: 50, aliases: ['gen', 'ge', 'gn'] },
  { id: 'exodus', name: 'Exodus', chapters: 40, aliases: ['exod', 'exo', 'ex'] },
  { id: 'leviticus', name: 'Leviticus', chapters: 27, aliases: ['lev', 'le', 'lv'] },
  { id: 'numbers', name: 'Numbers', chapters: 36, aliases: ['num', 'nu', 'nm', 'nb'] },
  { id: 'deuteronomy', name: 'Deuteronomy', chapters: 34, aliases: ['deut', 'deu', 'dt'] },
  { id: 'joshua', name: 'Joshua', chapters: 24, aliases: ['josh', 'jos', 'jsh'] },
  { id: 'judges', name: 'Judges', chapters: 21, aliases: ['judg', 'jdg', 'jg', 'jdgs'] },
  { id: 'ruth', name: 'Ruth', chapters: 4, aliases: ['rth', 'ru'] },
  { id: '1samuel', name: '1 Samuel', chapters: 31, aliases: ['1sam', '1sa', '1sm', '1s'] },
  { id: '2samuel', name: '2 Samuel', chapters: 24, aliases: ['2sam', '2sa', '2sm', '2s'] },
  { id: '1kings', name: '1 Kings', chapters: 22, aliases: ['1kgs', '1ki', '1kin', '1k'] },
  { id: '2kings', name: '2 Kings', chapters: 25, aliases: ['2kgs', '2ki', '2kin', '2k'] },
  { id: '1chronicles', name: '1 Chronicles', chapters: 29, aliases: ['1chron', '1chr', '1ch'] },
  { id: '2chronicles', name: '2 Chronicles', chapters: 36, aliases: ['2chron', '2chr', '2ch'] },
  { id: 'ezra', name: 'Ezra', chapters: 10, aliases: ['ezr'] },
  { id: 'nehemiah', name: 'Nehemiah', chapters: 13, aliases: ['neh', 'ne'] },
  { id: 'esther', name: 'Esther', chapters: 10, aliases: ['esth', 'est', 'es'] },
  { id: 'job', name: 'Job', chapters: 42, aliases: ['jb'] },
  { id: 'psalms', name: 'Psalm', chapters: 150, aliases: ['psalm', 'psa', 'ps', 'pslm', 'psm', 'pss'] },
  { id: 'proverbs', name: 'Proverbs', chapters: 31, aliases: ['prov', 'pro', 'prv', 'pr'] },
  { id: 'ecclesiastes', name: 'Ecclesiastes', chapters: 12, aliases: ['eccles', 'eccl', 'ecc', 'ec', 'qoh', 'qoheleth'] },
  { id: 'songofsolomon', name: 'Song of Solomon', chapters: 8, aliases: ['songofsongs', 'song', 'sos', 'so', 'canticles', 'canticleofcanticles'] },
  { id: 'isaiah', name: 'Isaiah', chapters: 66, aliases: ['isa', 'is'] },
  { id: 'jeremiah', name: 'Jeremiah', chapters: 52, aliases: ['jer', 'je', 'jr'] },
  { id: 'lamentations', name: 'Lamentations', chapters: 5, aliases: ['lam', 'la'] },
  { id: 'ezekiel', name: 'Ezekiel', chapters: 48, aliases: ['ezek', 'eze', 'ezk'] },
  { id: 'daniel', name: 'Daniel', chapters: 12, aliases: ['dan', 'da', 'dn'] },
  { id: 'hosea', name: 'Hosea', chapters: 14, aliases: ['hos', 'ho'] },
  { id: 'joel', name: 'Joel', chapters: 3, aliases: ['jl'] },
  { id: 'amos', name: 'Amos', chapters: 9, aliases: ['am'] },
  { id: 'obadiah', name: 'Obadiah', chapters: 1, aliases: ['obad', 'ob'] },
  { id: 'jonah', name: 'Jonah', chapters: 4, aliases: ['jnh', 'jon'] },
  { id: 'micah', name: 'Micah', chapters: 7, aliases: ['mic', 'mc'] },
  { id: 'nahum', name: 'Nahum', chapters: 3, aliases: ['nah', 'na'] },
  { id: 'habakkuk', name: 'Habakkuk', chapters: 3, aliases: ['hab', 'hb'] },
  { id: 'zephaniah', name: 'Zephaniah', chapters: 3, aliases: ['zeph', 'zep', 'zp'] },
  { id: 'haggai', name: 'Haggai', chapters: 2, aliases: ['hag', 'hg'] },
  { id: 'zechariah', name: 'Zechariah', chapters: 14, aliases: ['zech', 'zec', 'zc'] },
  { id: 'malachi', name: 'Malachi', chapters: 4, aliases: ['mal', 'ml'] },
  { id: 'matthew', name: 'Matthew', chapters: 28, aliases: ['matt', 'mat', 'mt'] },
  { id: 'mark', name: 'Mark', chapters: 16, aliases: ['mrk', 'mar', 'mk', 'mr'] },
  { id: 'luke', name: 'Luke', chapters: 24, aliases: ['luk', 'lk'] },
  { id: 'john', name: 'John', chapters: 21, aliases: ['joh', 'jhn', 'jn'] },
  { id: 'acts', name: 'Acts', chapters: 28, aliases: ['act', 'ac', 'actsoftheapostles'] },
  { id: 'romans', name: 'Romans', chapters: 16, aliases: ['rom', 'ro', 'rm'] },
  { id: '1corinthians', name: '1 Corinthians', chapters: 16, aliases: ['1cor', '1co'] },
  { id: '2corinthians', name: '2 Corinthians', chapters: 13, aliases: ['2cor', '2co'] },
  { id: 'galatians', name: 'Galatians', chapters: 6, aliases: ['gal', 'ga'] },
  { id: 'ephesians', name: 'Ephesians', chapters: 6, aliases: ['eph', 'ephes'] },
  { id: 'philippians', name: 'Philippians', chapters: 4, aliases: ['phil', 'php', 'pp'] },
  { id: 'colossians', name: 'Colossians', chapters: 4, aliases: ['col', 'co'] },
  { id: '1thessalonians', name: '1 Thessalonians', chapters: 5, aliases: ['1thess', '1thes', '1th'] },
  { id: '2thessalonians', name: '2 Thessalonians', chapters: 3, aliases: ['2thess', '2thes', '2th'] },
  { id: '1timothy', name: '1 Timothy', chapters: 6, aliases: ['1tim', '1ti'] },
  { id: '2timothy', name: '2 Timothy', chapters: 4, aliases: ['2tim', '2ti'] },
  { id: 'titus', name: 'Titus', chapters: 3, aliases: ['tit', 'ti'] },
  { id: 'philemon', name: 'Philemon', chapters: 1, aliases: ['philem', 'phm', 'pm'] },
  { id: 'hebrews', name: 'Hebrews', chapters: 13, aliases: ['heb'] },
  { id: 'james', name: 'James', chapters: 5, aliases: ['jas', 'jm'] },
  { id: '1peter', name: '1 Peter', chapters: 5, aliases: ['1pet', '1pe', '1pt', '1p'] },
  { id: '2peter', name: '2 Peter', chapters: 3, aliases: ['2pet', '2pe', '2pt', '2p'] },
  { id: '1john', name: '1 John', chapters: 5, aliases: ['1jn', '1jhn', '1joh', '1j'] },
  { id: '2john', name: '2 John', chapters: 1, aliases: ['2jn', '2jhn', '2joh', '2j'] },
  { id: '3john', name: '3 John', chapters: 1, aliases: ['3jn', '3jhn', '3joh', '3j'] },
  { id: 'jude', name: 'Jude', chapters: 1, aliases: ['jud', 'jd'] },
  { id: 'revelation', name: 'Revelation', chapters: 22, aliases: ['rev', 're', 'revelations', 'apocalypse', 'therevelation'] },
];

const ALIAS: Record<string, string> = {};
for (const b of BOOKS) {
  ALIAS[squash(b.name)] = b.id;
  ALIAS[b.id] = b.id;
  for (const a of b.aliases) ALIAS[a] = b.id;
}
ALIAS.psalms = 'psalms';

function squash(s: string): string {
  return s.toLowerCase().replace(/[\s.]+/g, '');
}

export interface ParsedReference {
  bookId: string;
  book: string;
  chapter: number;
  /** First verse. Absent means the whole chapter. */
  from?: number;
  /** Last verse, inclusive. Absent means a single verse (or the whole chapter). */
  to?: number;
  /** The reference as a reader would say it: "John 3:16", "Psalm 23", "Romans 8:38-39". */
  ref: string;
}

export function bookById(id: string): BookMeta | undefined {
  return BOOKS.find((b) => b.id === id);
}

/** "1 John", "I John", "First John", "1st John", "1John" all mean the same book. */
function normalizeBook(raw: string): string {
  let s = raw.trim().toLowerCase().replace(/\./g, ' ').replace(/\s+/g, ' ');
  s = s
    .replace(/^(first|1st)\s+/, '1 ')
    .replace(/^(second|2nd)\s+/, '2 ')
    .replace(/^(third|3rd)\s+/, '3 ')
    .replace(/^iii\s+/, '3 ')
    .replace(/^ii\s+/, '2 ')
    .replace(/^i\s+/, '1 ');
  return squash(s);
}

/**
 * Parse a human reference. Accepts "John 3:16", "john 3.16", "Jn 3:16-18",
 * "1 Cor 13", "Psalm 23", "Song of Songs 2:1", "Romans 8:38-39" (also with a long dash).
 * Returns null for anything it cannot read with certainty, and clamps
 * nothing: a chapter past the book is null, not chapter 1.
 */
export function parseReference(input: string): ParsedReference | null {
  if (typeof input !== 'string') return null;
  const s = input
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\s*:\s*/g, ':')
    .replace(/\s*-\s*/g, '-')
    .trim();
  const m = s.match(/^(.*?[a-zA-Z])\.?\s*(\d{1,3})(?:[:.](\d{1,3})(?:-(\d{1,3}))?)?$/);
  if (!m) return null;
  const bookId = ALIAS[normalizeBook(m[1])];
  const book = bookId ? bookById(bookId) : undefined;
  if (!book) return null;
  const chapter = parseInt(m[2], 10);
  if (!(chapter >= 1 && chapter <= book.chapters)) return null;
  const from = m[3] ? parseInt(m[3], 10) : undefined;
  let to = m[4] ? parseInt(m[4], 10) : undefined;
  if (from !== undefined && from < 1) return null;
  if (to !== undefined && from !== undefined && to <= from) to = undefined;
  const parsed: ParsedReference = { bookId, book: book.name, chapter, ref: '' };
  if (from !== undefined) parsed.from = from;
  if (to !== undefined) parsed.to = to;
  parsed.ref = canonicalReference(parsed);
  return parsed;
}

export function canonicalReference(p: Omit<ParsedReference, 'ref'>): string {
  const base = `${p.book} ${p.chapter}`;
  if (p.from === undefined) return base;
  return p.to === undefined ? `${base}:${p.from}` : `${base}:${p.from}-${p.to}`;
}

/** The key the WEB cache is stored under: "john.3.16-16". */
export function refKey(p: Omit<ParsedReference, 'ref'>): string | null {
  if (p.from === undefined) return null;
  return `${p.bookId}.${p.chapter}.${p.from}-${p.to ?? p.from}`;
}

export interface Verse {
  verse: number;
  text: string;
}

/**
 * The verses of a span from one chapter of a stored book. A span that runs
 * past the chapter is cut at the chapter's end, never padded; a span with
 * nothing in it is an empty list. Nothing is added to the words.
 */
export function selectVerses(chapter: readonly string[] | undefined | null, from?: number, to?: number): Verse[] {
  if (!chapter || !chapter.length) return [];
  const start = from ?? 1;
  const end = from === undefined ? chapter.length : Math.max(start, to ?? start);
  const out: Verse[] = [];
  for (let v = start; v <= end; v++) {
    const t = chapter[v - 1];
    if (typeof t !== 'string') break;
    const clean = t.trim();
    if (clean) out.push({ verse: v, text: clean });
  }
  return out;
}

/** One line from several verses, as the app's own verseLine does. */
export function joinVerses(verses: readonly Verse[]): string {
  return verses.map((v) => v.text).join(' ').replace(/[,;:]\s*$/, '');
}

export type Translation = 'KJV' | 'WEB';

const WEB_CACHE = WEB as Record<string, { ref: string; text: string }>;

/** The World English Bible words for a span, only when the repo's cache holds exactly that span. */
export function webPassage(p: Omit<ParsedReference, 'ref'>): { ref: string; text: string } | null {
  const k = refKey(p);
  if (!k) return null;
  const hit = WEB_CACHE[k];
  if (hit) noteReading({ ref: hit.ref, translation: 'WEB', text: hit.text });
  return hit ? { ref: hit.ref, text: hit.text } : null;
}

export function webPassageCount(): number {
  return Object.keys(WEB_CACHE).length;
}

/** A URL slug for a verse, the way the web pages name them: john-3-16. */
export function verseSlug(p: Omit<ParsedReference, 'ref'>): string {
  const book = p.book.toLowerCase().replace(/\s+/g, '-');
  if (p.from === undefined) return `${book}-${p.chapter}`;
  return `${book}-${p.chapter}-${p.from}`;
}
